### ISSUE TITLE
PK filters only work for features, not for meta items

### ISSUE THREAD

**Issue by olsen232** [koordinates/kart#219]
`sno diff datasetA` show all diffs in dataset A
`sno diff datasetA:123` shows the diff for a particular feature (plus any meta diffs for datasetA)
`sno commit datasetA` commit all diffs in dataset A
`sno commit datasetA:123` commit the diff for a particular feature (plus any meta diffs for datasetA)

So filters always include meta items. There's no way to use the filters to exclude meta items, or to contain exclusively meta items. If there was it would look something like this:

`sno X datasetA` matches the entire dataset
`sno X datasetA:meta` matches only meta items
`sno X datasetA:feature` matches only features
`sno X datasetA:meta:title` matches a particular meta item
`sno X datasetA:feature:123` or `datasetA:123` matches a particular feature item (doesn't match meta items)

There is one area of this that would need some extra care taken - committing a feature change while there are still uncommitted schema changes for that schema should probably not be allowed. Until the current schema is committed, committing a feature which uses that schema isn't guaranteed to store all of its fields, which is surprising and probably bad.

**Comment by craigds** [comment]
I think my PR addresses all of this. @olsen232 concur?
