### ISSUE TITLE
startup is a bit slow (200-600ms)

### ISSUE THREAD

**Issue by craigds** [koordinates/kart#405]
`kart branch` (in a non-repo directory) spends 600ms loading code before it can give me an error message. This seems consistent across various commands. Built Kart on macOS seems faster than dev Kart, presumably due to pyinstaller being faster at doing imports, but is still consistently >200ms.

It seems important (for scripted usage especially) that we trim that startup time down - perhaps 200ms would be acceptable. Seems unlikely we'd get below 100ms without rewriting (the entrypoint at least) in a compiled language.

I used https://github.com/nschloe/tuna to do a basic profile and it seems like itt's all just doing regularish python imports. Interestingly quite a bit of the time is in sqlalchemy:

* 10% in `working_copy/*.py`
* 23% loading sqlalchemy

1. It might be helpful to just defer import of workingcopy/* and sqlalchemy until we need to do something with the working copy.

2. Perhaps we could segregate the startup by command: rather than loading all the commands on startup we could just load the one that's being invoked at present. This seems difficult to do with Click though.

**Comment by craigds** [comment]
another idea: write the basic `sno` entrypoint in go, and delegate most commands to python (just execvp the existing python entrypoint I guess).

Commands that just execvp to `git` can trivially be rewritten in Go to save on startup overhead, and perhaps over time other commands can move to Go too.

I say Go because it's reasonably pythonic, high level and has a pretty good package ecosystem, and [`git2go`](https://github.com/libgit2/git2go) looks quite complete. And @olsen232 is already quite familiar with it. Open to other language suggestions.

If we proceed on that path we should do some performance comparison of git2go vs pygit2 for large repos.

**Comment by pfw** [comment]
`kart helper` has been released in v0.11.5. This is c client to a long running, forking process that does the actual kart work.
