### ISSUE TITLE
Removing all features of a layer causes error when merging

### ISSUE THREAD

**Issue by volaya** [koordinates/kart#506]
To reproduce:

- Create a repo and add a layer with some features
- Create a new branch
- In the new branch, remove all features from the layer and commit
- switch back to main branch and try to merge the new branch onto it.

This workflow is already implemented in a test in the Kart QGIS plugin test suite, and the error trace can be found here:

https://github.com/volaya/kart-qgis-plugin/runs/4237417438?check_suite_focus=true#step:3:548

The test that causes this error can be found here:

https://github.com/volaya/kart-qgis-plugin/blob/main/kart/tests/test_kartapi.py#L233

**Comment by olsen232** [comment]
Fixed at 7f90181
