### ISSUE TITLE
Kart CI tests running on github actions don't use kart's git

### ISSUE THREAD

**Issue by olsen232** [koordinates/kart#509]
When you install kart, it comes bundled with a git. You can run that git in action running eg `kart git --version`. The bundled git will be somewhere in the folder where kart is installed. This seems to be working on all platforms.

However, that is not working during Kart's CI tests on the windows platform, so any unit test that requires kart to have a specific version of git with specific functionality, is liable to fail on windows. (This hasn't happened in practise until now, when I'm trying to bundle a custom git with kart).

https://github.com/koordinates/kart/runs/4259809997?check_suite_focus=true has an extra unit test that doesn't even try to pass, but it simply prints where the kart and `kart git` binaries are. If they are close by each other, this is a good sign, if they are on opposite sides of the filesystem, it probably means we are using the wrong git.

On linux it outputs this:
`/home/runner/work/kart/kart/venv/bin/kart`
`/home/runner/work/kart/kart/venv/bin/git`

And on macos it outputs tihs:
`/Users/runner/work/kart/kart/venv/bin/kart`
`/Users/runner/work/kart/kart/venv/bin/git`

But on windows it outputs this:
`D:\a\kart\kart\venv\Scripts\kart.exe`
`C:\Program Files\Git\bin\git.exe` <- this is the wrong git

(That git location is the first git location when running `where git` from within kart, which if I understand correctly, will be the git.exe which `kart git` will run. I have other reasons for thinking that we are finding the wrong git - I bundled a custom git, which seemed to work when I installed kart, but it didn't work during the CI test on GH actions).

**Comment by olsen232** [comment]
Perhaps the PATH is wrong, something like that - but maybe @rcoup can tell me what has gone wrong - perhaps there is some tool that is supposed to set the PATH that isn't doing so, or, I don't know

**Comment by rcoup** [comment]
Path/tool setup happens here: https://github.com/koordinates/kart/blob/master/kart/__init__.py

(the implementation changes slightly with cmake, but the setup still happens)

Wonder if that's not happening in tests somehow?

**Comment by rcoup** [comment]
I added more debugging: https://github.com/koordinates/kart/runs/4264945680?check_suite_focus=true

`kart.__init__` effectively looks for it at `venv/git/cmd/git.exe`

Where's the custom git being put in the venv / vendor bundle? 

AFAICS it's there in the *installer* on master and v0.10.6 at `<kart-root>/git/cmd/git.exe`

In the *vendor bundle*, `git` is a top-level folder alongside `env`... I have a feeling it should be `env/git/` so it ends up at `venv/git/`. Not sure when that might have changed...

**Comment by olsen232** [comment]
I think this is an existing issue - I've detected it because I was experimenting with a custom git, but, I think it was already happening before. Not sure since when, I don't think I've ever touched how git is built or configured on windows but I may be wrong. That's some useful info you've given me, I can look into it some more

**Comment by olsen232** [comment]
Looks like we're installing all the vendor libraries to dist\env - as opposed to macos and linux where we install them to vendor\env.
I'll experiment with changing that. There's a risk that I'll make things better during CI testing, but worse when you run the MSI installer

**Comment by rcoup** [comment]
The installer behaviour is in the `platform/` makefiles & `kart.spec`. Should be fairly obvious what it's doing.

**Comment by olsen232** [comment]
Fixed at d778b0726536397002dbd7a099b019267e77d3bb
