### ISSUE TITLE
Comparison "git/kart clone" 

### ISSUE THREAD

**Issue by dkastl** [koordinates/kart#533]
I enjoy trying out Kart and for testing I created a repository on Github: https://github.com/Georepublic/kart-repo

I thought to share the following observations when I compare `git clone` to `kart clone`:

### Case 1: cloning with `ssh`:

* **Git**

```
git clone git@github.com:Georepublic/kart-repo.git
Cloning into 'kart-repo'...
...
```
-> Creates a directory `kart-repo`

* **Kart**

```
kart clone git@github.com:Georepublic/kart-repo.git
Cloning into '/home/test/kart-repo.git/.clone'...
...
Creating working copy at kart-repo.gpkg ...
```
-> Creates a directory `kart-repo.git` 

Is this intentional to add `.git` to the directory name by default? I only know this when I run `git clone --mirror ...`.

### Case 2 cloning with `https`

* **Git**

```
git clone https://github.com/Georepublic/kart-repo.git
Cloning into 'kart-repo'...
...
```
-> Creates a directory `kart-repo`

* **Kart**

```
kart clone https://github.com/Georepublic/kart-repo.git
Cloning into '/home/test/kart-repo.git/.clone'...
fatal: unable to access 'https://github.com/Georepublic/kart-repo.git/': error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```
-> Returns an error

### Versions

* Kart

````
kart --version
Kart v0.10.7, Copyright (c) Kart Contributors
» GDAL v3.3.2; PROJ v6.3.0
» PyGit2 v1.7.0; Libgit2 v1.3.0; Git v2.33.GIT
» SQLAlchemy v1.4.11; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.1; Libpq v10.0.12
» SpatialIndex v1.9.3
```

* OS: Ubuntu 21.04

**Comment by craigds** [comment]
> Is this intentional to add .git to the directory name by default? I only know this when I run git clone --mirror ....

no, that looks like an oversight; should be an easy fix 👍 

> fatal: unable to access 'https://github.com/Georepublic/kart-repo.git/': error setting certificate verify locations:

It looks like the Linux build [has some special handling for CA cert bundles](https://github.com/koordinates/kart/blame/master/kart/__init__.py#L126-L131). I have a fairly vague knowledge of how this works; perhaps @rcoup can chime in?

**Comment by craigds** [comment]
Both https and ssh cloning methods produce a `kart-repo.git` folder for me
