### ISSUE TITLE
Spatial filtering: Can't enlarge beyond original spatial filter

### ISSUE THREAD

**Issue by olsen232** [koordinates/kart#537]
This issue involves spatial filtering which will be launched with Kart 0.11.0

During a clone, the user can set a spatial filter to limit which features are set.
Any time after a clone, the user can modify the spatial filter so that only some subset of the features fetched are actually written to the working copy and shown to the user - the other features are hidden. The limitation is that any spatial filter chosen cannot extend beyond the original spatial filter that was active during the clone, since those features are simply not present on disk. The workaround is to clone a new repository with the larger spatial filter. It would of course be preferable if it was possible to enlarge the spatial filter after cloning, but there are two reasons why this is difficult and it is not yet supported.

Firstly, it is difficult to convince git to refetch data that it thinks it already has. During the clone, git knows of some number of branch heads that it needs to clone. It takes those branch heads and follows all the links - all of the commits that are referenced including ancestors, all of the root trees of those commits, and all of the trees and blobs that are referenced directly or indirectly by those trees. When we apply a spatial filter, we cause some of those blobs to be skipped instead of fetched, but otherwise the process remains the same.
If we ask git to repeat the fetch, but with a different spatial filter active, it will give up immediately - it sees that all of the branch heads and their ancestors have already been fetched. Git doesn't really support recloning a partial clone with a different filter active and doesn't understand that the operation would have a different result this time. The workarounds suggested online are the same as suggested above - either reclone with a fresh repo, or, delete the existing packfiles and then reclone in the existing repo. Either way, the clone will start from scratch.

The other difficulty is the difficulty of specifying exactly which features we want. Git is able to avoid resending blobs that the client already has by communicating about which commits the client already has. Ideally we would modify our spatial filter so it can do the same sort of thing: fetch all the features in envelope NEW except those that are in envelope OLD, since we envelope OLD was the previous spatial filter and was already fetched. However, we have to be careful that we don't miss any features that are in envelope OLD and have been added since last time a fetch was performed.

For instance, if the user clones branch heads A, B, and C, with spatial filter OLD, then they have everything they need. This is working right now.
But if the user then wants to perform a refetch with spatial filter NEW, and the branch heads A, B, and C on the server have had more commits added and so are now A', B' and C', then we will need to fetch all of the following (but perhaps in two stages, one where they change their spatial filter and another when they run kart fetch):
- Firstly, we need to refetch A, B, C (the old branch heads) with two-envelope-subtraction spatial filter (NEW minus OLD)
- Secondly, we need to fetch A', B', C' (but stopping at A, B, C) with single-envelope spatial filter NEW

 Specifically we need to make sure we don't miss the new features that are added in A', B', C' (added since A, B, C) and that are contained by both OLD and NEW envelopes.

A simpler method would be to just reclone all the branch heads from scratch using the new spatial filter. This has the same efficiency as the workaround however, in that it can refetch some of the same features again. Depending on the use case, not using spatial filtering at all during the clone operation could be more efficient.

**Comment by rcoup** [comment]
> A simpler method would be to just reclone all the branch heads from scratch using the new spatial filter.

I think this is a reasonably pragmatic approach. Repack will remove duplicate objects after a fetch, so it's a temporary state. 

How can we initiate a fetch and tell git that we "have nothing"?

**Comment by olsen232** [comment]
Maybe by renaming / deleting all the packfiles.
There's quite possibly another way but it depends at what level the negotiation between client and server happens - we may or may not be able to call a low level git command which does the fetch and give it different / "wrong" arguments about the state of the client - or we may not, perhaps "git fetch" is the lowest level git command we have easy access to and it won't refetch what we already have. We could also modify git fetch to add this option in our git fork, but this would be more work.

**Comment by olsen232** [comment]
Fixed at 0bc41adfc73a7158f4ef4742456592fd7d7aff50
