### ISSUE TITLE
Spatial filtering: loose objects / promisor packfile issues

### ISSUE THREAD

**Issue by olsen232** [koordinates/kart#552]
Further thinking about #550 helped me realise the following issue, which I just managed to reproduce and it is indeed an issue. I'll start with some steps to reproduce:

1. Create a spatially-indexed repo with a small number of features - perhaps 10. They should have integer PKs.
2. Do a spatially filtered clone that only contains some of the features. Let's say the even-numbered ones, but it doesn't matter.
3. Modify or delete some of the features that you can see in that repo (for instance, let's delete PK 10).
4. Commit the change.
5. Run `kart --create-workingcopy` to recreate the working copy from scratch.
This will crash with something like`KeyError: 'object not found - object is missing (d5f1ee5c268963a259815304725476ecb1a38c22)'`

The issue:
There is a tree called something like `my-dataset/.table-dataset/feature/A/A/A/A`. For a small dataset like the one you created, this tree directly contains all features that exist. After the commit, there is a new version of this tree that still directly contains all features that now exist. Some of these features are local and edited, others are remote and promised. This tree is in your local loose objects store. Your repository is now effectively corrupt - it is against the rules that a local loose object refers directly to a missing+promised object - there is no way to tell if such an object is promised or not, since local loose objects cannot be marked as "promisor".
This corruption is made apparent only when we run a command that tries to read the entire dataset, like recreating the working copy. Any type of diffing works fine, since the diff will skip over anything that hasn't changed. These features haven't changed, so we don't try to read them.

Why it's easy to miss:
Creating the working copy from the first commit of the clone (which is not corrupt) and then checking out the latest commit from there still works, since Kart only rewrites the features that have changed, and diffing is working fine. It's just doing a full-read of the dataset at a particular commit that causes Kart to freak out about the missing feature which is not "promised". This is also why it's possible to continue working with the repo including doing more diffs, checkouts, and commits - none of these require rewriting the working copy from scratch and therefore reading the entire dataset including the unchanged-but-now-corrupt features.

**Comment by olsen232** [comment]
https://git-scm.com/docs/partial-clone/2.25.0#_future_work mentions this kind of issue in passing: 

> Investigate the need to handle loose promisor objects.
> 
> Objects in promisor packfiles are allowed to reference missing objects that can be dynamically fetched from the server. An assumption was made that loose objects are only created locally and therefore should not reference a missing object. We may need to revisit that assumption if, for example, we dynamically fetch a missing tree and store it as a loose object rather than a single object packfile.
> 
> This does not necessarily mean we need to mark loose objects as promisor; it may be sufficient to relax the object lookup or is-promisor functions.

The example given is if a missing tree is fetched and stored as a loose object (which isn't supported) - the issue we have here (creating a new loose tree that contains promised objects) isn't mentioned at all. So, we're on our own.

One solution would be to repack all the commits made locally as promisor packfiles.

**Comment by rcoup** [comment]
Rewording the issue for my own understanding:

> The issue is we create a new tree (A’) from an existing tree A, and A & A’ point to a pre-existing blob B. And while A was physically present in a promisor packfile, B is not (ie: it is promised).
>
> So now the loose object A’ is invalid because it directly refers to missing object B: tree A was present in a promisor packfile and so referring to missing B was fine, but A’ is not.
>
> The same issue applies to several object relations: commits→trees, trees→trees, trees→blob, (tag->blob?). For Kart’s spatially filtered clones this only arises in tree→blob. (edited)

**Comment by olsen232** [comment]
Fixed at 6478332147fc9059e7f258fd61c9172fdbdf6694 - we write packfiles and mark them as promisor when working in a spatially filtered clone
