### ISSUE TITLE
sqlite_enable_load_extension disabled; CMake configuration fails

### ISSUE THREAD

**Issue by judafe** [koordinates/kart#600]
**CMake produces an error**

I am building Kart on my macOS by following the instructions in  [kart/CONTRIBUTING.md](https://github.com/koordinates/kart/blob/master/CONTRIBUTING.md).
The configuration step with CMake produces the following error:

```
 CMake Error at vendor/CMakeLists.txt:62 (message):
   Found SQLite3, but sqlite3_enable_load_extension is disabled.
```

Sqlite3 was installed via homebrew, and I modified the CMake Cache to direct it to the correct installation.
```
//Path to a file.
SQLite3_INCLUDE_DIR:PATH=/opt/homebrew/Cellar/sqlite/3.38.2/include

//Path to a library.
SQLite3_LIBRARY:FILEPATH=/opt/homebrew/Cellar/sqlite/3.38.2/lib
```

**To Reproduce**
The error was produced while following the instructions in CONTRIBUTING.md.
To change the sqlite path variables, do the following...
1. Go to the build folder: ```cd kart/build```
2. Open CMake curses interface: ```ccmake ..```
3. Toggle advanced mode to on by clicking 't'
4. Find the SQLITE_LIBRRY and SQLITE3_INCLUDE entries.  
5. Change entry names to appropriate homebrew directories 

**Output**
I am pasting a snippet from the CMakeError.log:
```
Run Build Command(s):/usr/bin/make -f Makefile cmTC_eb801/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_eb801.dir/build.make CMakeFiles/cmTC_eb801.dir/build
Building C object CMakeFiles/cmTC_eb801.dir/CheckSymbolExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.2 -MD -MT CMakeFiles/cmTC_eb801.dir/CheckSymbolExists.c.o -MF CMakeFiles/cmTC_eb801.dir/CheckSymbolExists.c.o.d -o CMakeFiles/cmTC_eb801.dir/CheckSymbolExists.c.o -c /Users/juancheeto/Desktop/kart/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/Users/juancheeto/Desktop/kart/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: use of undeclared identifier 'sqlite3_enable_load_extension'
  return ((int*)(&sqlite3_enable_load_extension))[argc];
                  ^
1 error generated.
make[1]: *** [CMakeFiles/cmTC_eb801.dir/CheckSymbolExists.c.o] Error 1
make: *** [cmTC_eb801/fast] Error 2
```

**Version Info **
 - macOS Monterey 12.2
 - Version: -?

**Comment by amal-thundiyil** [comment]
Hello @judafe! I am not sure if your problem is solved by using `make`. Nevertheless, it sounds like your `sqlite` was built without extension loading support (see [docs](https://www.sqlite.org/c3ref/enable_load_extension.html)). What I had done to solve a similar problem using `brew` on `macOS` was to run:
```sh
brew install sqlite
```
You can put sqlite in your path by either editing your profile file to extend the path, or else by adding a link to the updated `sqlite3` in `/usr/local/bin`. In my case I used:
```
ln -s /usr/local/opt/sqlite/bin/sqlite3 /usr/local/bin/
```
However if just doing this doesn't work for you, I found [this guide](https://www.cafe-encounter.net/p3244/installing-and-using-sqlite-extensions-on-macos-and-maybe-windows-linux-too) online which might be something you want to look into. I hope this does solve the issue, if not, feel free to reach back. Cheers!

**Comment by hamishcampbell** [comment]
I've also run into this. 

cmake is searching for the homebrew installed of sqlite3 in `/usr/local/opt/sqlite3` but it isn't present there. Changing this to `/opt/homebrew/opt/sqlite` lets my build proceed.

(Apple / amd64, as of 947d75c9ccd192a173d14e59e878976a99a9a3a7)

**Comment by hamishcampbell** [comment]
Unclear if related, but it subsequently fails on:

```
CMake Error at /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY
  PostgreSQL_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/FindPostgreSQL.cmake:269 (find_package_handle_standard_args)
  vendor/CMakeLists.txt:78 (find_package)

```
