### ISSUE TITLE
FR: A way to list tables that are in the working copy area but are not tracked by kart

### ISSUE THREAD

**Issue by olsen232** [koordinates/kart#609]
It's possible for the user to create tables inside the working copy that Kart uses, but if they do so, Kart will never take any notice of them, and there is currently no correct way to add them to the Kart repository (you could try importing such a table, but unless you rename it during import, the imported data will collide with the original table, which will cause the command to fail and add to the user's confusion). See https://github.com/koordinates/kart/issues/249

It is possible to get a list of the tables that Kart is currently managing (with `kart data ls`) but there is no way for the user to get a list of any tables in the WC that Kart is not tracking.
This would be a useful first step to implementing https://github.com/koordinates/kart/issues/249
Perhaps `kart status --list-untracked-tables`

There is code for listing tables for each of the four currently-supported types of working copy - see:
https://github.com/koordinates/kart/search?q=list_tables&type=code
It should be possible to make this change with very little or no code that is specific to a certain working copy type, if you use this interface that already exists.

**Comment by Zumitify** [comment]
Thanks @olsen232, for creating this new enhancement issue. 

> to list untracked files you might just want to add something to the various working copy classes to directly list tables from the database, and then filter out ones that are already datasets.

The approach mentioned in this [comment](https://github.com/koordinates/kart/issues/249#issuecomment-1100939800) by @craigds seems like the most straightforward way to tackle this.
Thanks.
