### ISSUE TITLE
`kart data version` provides a URL to a non-existant page

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/kart#647]
The command `kart data version` lists the current format specification for the repository.

It outputs the following:

```
This Kart repo uses Datasets v3
(See https://github.com/koordinates/kart/blob/master/docs/DATASETS_v3.md)
```

However the docs no longer live at that location, and should probably be updated to:

`https://docs.kartproject.org/en/latest/pages/development/datasets_v3.html#datasets-v3`

**Version Info **

```
Kart v0.11.3, Copyright (c) Kart Contributors
» GDAL v3.4.0; PROJ v6.3.0
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.33.GIT
» SQLAlchemy v1.4.36; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.1; Libpq v14.0.3
» SpatialIndex v1.9.3
```

**Comment by olsen232** [comment]
Also there's a link to the spatial filter doc in our docs that has moved - https://github.com/koordinates/kart/blob/master/docs/SPATIAL_FILTERING.md
is now at https://docs.kartproject.org/en/latest/pages/command_reference.html#spatial-filtering
