### ISSUE TITLE
Makefile and friends use /usr/local, Home-brew on Apple Silicon installs by default at /opt/homebrew

### ISSUE THREAD

**Issue by pfw** [koordinates/kart#650]
**Describe the bug**

Build requires /usr/local currently but at least by default on Apple Silicon requirements will be in /opt/homebrew

**To Reproduce**
Homebrew install on Apple Silicon machine

**Expected behaviour**
It should probably determine the prefix automatically.

**Comment by rcoup** [comment]
Yes.

The Makefile stuff is a messy pile of hacks already, I'm tempted to punt this until after we switch fully to CMake, in which case it'll be much saner to deal with. 

Out of curiosity, if you `s#/usr/local#/opt/homebrew# Makefile vendor/Makefile vendor/*/Makefile platforms/macos/Makefile` does it _build_ on osx+arm64? If so, a patch substituting in `brew --prefix` would be ok.

**Comment by pfw** [comment]
Changing those paths gets a bit further but things still go off the rails with explicit definitions for python versions and platform tags, eg. 

https://github.com/koordinates/kart/blob/e21276ab705fbc072f558213ee2c3812c9ee8bb0/vendor/gdal/Makefile#L20

Sorting all of this out when CMake is used sounds like the best given the multitude of places that need touching. Out of interest what is required on the CMake front? It looks to build fine, is it just the post build steps, packaging etc.?

**Comment by olsen232** [comment]
Closing this as won't fix - the new build system still has issues but we're not going back to Makefiles now
