### ISSUE TITLE
kart diff between commits without working copy errors

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart#666]
**Describe the bug**

`kart diff` errors in some situations without a working copy, even when the diff doesn't involve one.

**To Reproduce**

```console
$ kart clone --no-checkout me@example.com/repo
$ kart diff -o json HEAD^1 HEAD
Error: Cannot generate working copy diff:
Repository has no working copy.
  (use "kart create-workingcopy")
```

Same occurs between any two commits/refs/trees, it's not related to `HEAD` specifically. Using `A...B`/`A..B` works fine, though produces different results (and `..` doesn't work for trees)

**Expected behaviour**

Show the diff between two arbitrary commits/trees, which shouldn't relate to the working-copy.

**Version Info**
 - OS: macOS 12.2.1
 - Version: v0.11.4.dev0 @ 97ef458a36fc495454e75469a2059a9569a3021a

**Comment by olsen232** [comment]
I think we only support COMMIT..COMMIT and COMMIT...COMMIT for specifying a commit range.
If you supply them as two args I think it parses it as COMMIT PATHSPEC.

But yeah we should support both for consistency with git - although git always supports so many weird things
