### ISSUE TITLE
config: tab completion setup issues

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart#701]
**Describe the bug**

@amal-thundiyil 

A couple of minor annoyances setting up tab completion:

```console
$ kart config
usage: git config [<options>]
...
```

Expected to see the same as `kart config --help`, or some combination of the two — maybe the key arguments from `git config`, and an explanation that anything you can pass to `git config` will also work for `kart config`?

```console
kart config --help
Usage: kart_cli config [OPTIONS] [ARGS]...

  Get and set repository or global options

Options:
  --install-tab-completion [bash|zsh|fish|powershell|pwsh|auto]
                                  Install tab completion for the specific or
                                  current shell
  --help                          Show this message and exit.
```

Then:
```console
$ kart config --install-tab-completion
Error: Option '--install-tab-completion' requires an argument.
```
I think the default should be `auto`

**Version Info **
 - OS: macOS
 - Version: v0.11.6.dev0

**Comment by craigds** [comment]
fixed by #703
