### ISSUE TITLE
LFS pre-push hook breaks for bare clones when pushing to new ref

### ISSUE THREAD

**Issue by craigds** [koordinates/kart#736]
**Describe the bug**

Cloning a repo with `X_KART_POINT_CLOUDS=1` and `--bare` sets up a pre-push hook. That hook fails if you later run `kart push` *to a new ref* because the LFS objects aren't present locally.

**To Reproduce**
Steps to reproduce the behaviour:
1. `X_KART_POINT_CLOUDS=1 kart clone --bare <url>`
2. Notice the presence of a `hooks/pre-push` file
3. `kart push origin HEAD:refs/heads/new-branch` (the new-branch thing is important; it only fails if the branch doesn't exist on the remote!)

**Expected behaviour**

It should push. Since I haven't modified any LFS objects I don't expect git-lfs to do anything

**Output**

```
$ kart push origin HEAD:refs/heads/new-branch
Unable to stat local media path: stat /tmp/tmpj7o0aomj/lfs/objects/f8/45/f845171af3e8a1aa3afd77bcef19ba1569a3f41558575d7902a0eb737c2b4b1b: no such file or directory
Error: There was a problem with git-lfs push: Command '['git-lfs', 'push', 'origin', '--object-id', 'f845171af3e8a1aa3afd77bcef19ba1569a3f41558575d7902a0eb737c2b4b1b']' returned non-zero exit status 2.
error: failed to push some refs to '<...snip...>'
```

**Version Info **

Kart master (v0.11.6.dev0+ci.4326.git71c38439) on Ubuntu 18.04

**Comment by craigds** [comment]
I dug into this a bit more. Git calls the pre-push hook and passes it the local and remote refs and tip OIDs. It's not clearly documented in git help but the source sample pre-push makes it clearer: https://github.com/git/git/blob/319605f8f00e402f3ea758a02c63534ff800a711/templates/hooks--pre-push.sample#L17


So if pushing to a new remote ref, the `remote oid` there will be `0000000000000000000000000000000000000000`. kart then basically lists the objects modified in the entire history of the local commit, and thus figures out that it should push all LFS objects.

Pushing all LFS objects works fine in many cases when there is a working copy because they would all have been fetched already to create the working copy. So the push attempts to push a bunch of files, realises that they haven't changed and noops.

However, it fails when:
- there is no working copy (ie this ticket) because nothing ever fetched those objects
- there is a working copy but the log history contains more objects than the working copy (ie a previous commit in the history deleted some objects, and then we cloned the repo but didn't end up checkouting the deleted objects). So the lfs push will fail to push objects then too.

I'm not sure what the right fix is. If this only affected bare repos then it probably wouldn't be a big deal, but sooner or later someone will hit this problem with any normal pointcloud repo.

I think ideally `kart lfs+ pre-push` would interact with the server to determine what object hashes actually need pushing, before it tries to access the content of those files locally. I'm not familiar with the LFS protocol enough to figure out if this is easy or a good idea.

**Comment by olsen232** [comment]
Correct, this is a problem in general, not just with bare repos. Here is another way to reproduce it:
- Clone a repo, delete some LFS tiles, commit the change. Run `kart lfs+ gc` to clean up any currently unneeded tiles. Then checkout a new branch at the same commit, and try to push the branch. Again, it will try to push from `00000...`, so it needs all tiles in the current commit's history, but the ones you deleted will be missing, so it will fail with the same error.

I'm not sure what the standard LFS implementation does in this or similar situations - I'll look into it.
As you say, liaising with the server somehow to work out if objects are actually missing remotely or not would be a fix, if it can be arranged

**Comment by olsen232** [comment]
Should be fixed as of https://github.com/koordinates/kart/pull/750
