### ISSUE TITLE
kart tab completion doesn't complete on files

### ISSUE THREAD

**Issue by pfw** [koordinates/kart#743]
**Describe the bug**
When tab completion is installed kart commands are completed but file path arguments are not completed.

**To Reproduce**
Steps to reproduce the behaviour:
1. `kart install tab-completion`
2. Go to a kart repo
3. `kart imTAB` will complete the `import`
4. `kart import F` will not complete a file starting with F

**Expected behaviour**
Where file paths are possible arguments to kart commands they should be able to be completed.

**Output**

https://user-images.githubusercontent.com/92163/204939083-b6c08f08-6011-4622-a2f3-48a791dd9e19.mov

**Version Info **
```
Kart v0.11.6.dev0, Copyright (c) Kart Contributors
» GDAL v3.4.0; PROJ v6.3.0
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.33.GIT
» SQLAlchemy v1.4.44; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.1; Libpq v14.0.4
```

**Comment by olsen232** [comment]
This as fixed as of #746
