### ISSUE TITLE
sql exception creating postgres workingcopy with NULL numeric fields

### ISSUE THREAD

**Issue by enricofer** [koordinates/kart#862]
**Describe the bug**
I commit a change to a postgis dataset introducing new rows with some columns left to NULL, everything seems right, even in kart fsck but cloning the dataset ( or creating a postgres workingcopy ) a sqlalchemy exception is thrown (reported below). Inspecting the exception trace it appears that the problem is with numeric fields with NULL values.
In a previous commit I solved the issue manually assigning a valid numeric value (see commit 7f735b40aa83fd67493abacb07f0e20888e4ad29 in the provided faulty repo) but after a new commit this solution is no longer working (see provided patch patch_no_null.json )
The issue affects only postgres repos. Geopackage repos seems to be immune.

**To Reproduce**
Steps to reproduce the behaviour:
1. download the faulty repo: https://pashare.comune.padova.it/index.php/s/m6QWNXRCeBYLpPF
2. creating a gpkg working copy `kart create-workingcopy RIGHT_DATASET.gpkg` should be ok
3. try to create a postgres working copy: `kart create-workingcopy  postgresql://[user]:[passwd]@[host]:[port]/[db]/[schema]`
4. See error below
5. try to patch NULL numeric fields with numeric values: `kart apply patch_no_null.json`
6. retry step 3 and get the same error

**Expected behaviour**
Getting a postgres workingcopy

**Output**
Creating PostGIS working copy at postgresql://postgres@localhost:5433/VISIO/SIR2_CONTRODEDUZIONI ...
Writing features for dataset 1 of 26: PI_CS_previsioni_puntuali
PI_CS_previsioni_puntuali: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 4639.08F/s]
Writing features for dataset 2 of 26: impa_A0_CS
impa_A0_CS: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 5668.62F/s]
Writing features for dataset 3 of 26: b0501061_Architetture900
b0501061_Architetture900: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 159/159 [00:00<00:00, 11712.02F/s]
Writing features for dataset 4 of 26: b0501051_PerimetriCS
b0501051_PerimetriCS: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 187/187 [00:00<00:00, 8008.24F/s]
Writing features for dataset 5 of 26: PI_CS_limitiUP
PI_CS_limitiUP: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17750/17750 [00:01<00:00, 11826.33F/s]
Writing features for dataset 6 of 26: b0501051_ViabProg
b0501051_ViabProg: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 5412.78F/s]
Writing features for dataset 7 of 26: b0501041_Perimetri
b0501041_Perimetri: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 5644.50F/s]
Writing features for dataset 8 of 26: b0501071_EdificiIncongrui
b0501071_EdificiIncongrui: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 95/95 [00:00<00:00, 12681.70F/s]
Writing features for dataset 9 of 26: a0102011_ConfiniComunali
a0102011_ConfiniComunali: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1457.37F/s]
Writing features for dataset 10 of 26: b0501063_CaseColoniche
b0501063_CaseColoniche: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 7718.39F/s]
Writing features for dataset 11 of 26: PI_CS_aree_scoperte
PI_CS_aree_scoperte: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4966/4966 [00:01<00:00, 3931.02F/s]
kart helper: unhandled exception
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1880, in _execute_context
  File "sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
  File "psycopg2/extras.py", line 1289, in execute_values
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: ""
LINE 1: ...412497ffe0504f3a416e348057b8325341'::bytea, '15', '', '0', '...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kart/helper.py", line 236, in helper
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "kart/cli_util.py", line 72, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "kart/create_workingcopy.py", line 228, in create_workingcopy
  File "kart/create_workingcopy.py", line 111, in create_tabular_workingcopy
  File "kart/working_copy.py", line 184, in create_parts_if_missing
  File "kart/tabular/working_copy/base.py", line 1348, in reset
  File "kart/tabular/working_copy/base.py", line 1040, in write_full
  File "sqlalchemy/orm/session.py", line 1714, in execute
  File "sqlalchemy/engine/base.py", line 1705, in _execute_20
  File "sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
  File "sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
  File "sqlalchemy/engine/base.py", line 1943, in _execute_context
  File "sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
  File "sqlalchemy/util/compat.py", line 211, in raise_
  File "sqlalchemy/engine/base.py", line 1880, in _execute_context
  File "sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
  File "psycopg2/extras.py", line 1289, in execute_values
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type numeric: ""
LINE 1: ...412497ffe0504f3a416e348057b8325341'::bytea, '15', '', '0', '...
                                                             ^

[SQL: INSERT INTO "SIR2_CONTRODEDUZIONI"."PI_CS_aree_scoperte" (auto_pk, geom, "LIVELLO", "ST", "SA", "W", "NAM", "ISOLATO", "UNITAED", "UNITAEL", "ATTRFAB", "PORTICO", "NUMALLO", "NUMALTR", "NUMPIAN", "AREPERT", "CONSERV", "SEMINTE", "TIPOGODI", "TIPOUED", "DESUSAS", "SUPERF", "DATAUAG", "DESCOPE", "TIPOLED", "TRASFED", "NORMA", "DESTPIAN", "CATEDIFI", "VINCOL1", "ART1", "VINCOL2", "ART2", "TIPOPRO", "NOTESTO", "NOTA1", "NOTA2", "NOTA3", "NOTA4", "NOTA5", "NOTA6", "NOTA7", "NOTA8", "NOTA9", "NOTA10", "NOTA11", "PARSUOLO", "MANINSTO", "TIPOLE1", "TRASFE1", "CLASSE", "TIPOLIN", "TIPOLI1", "TIPOLI2", "DESSER", "DESPRO", "SISBAS", "STRUATT", "PIANO1", "PIANO2", "PIANO3", "PIANO4", "URBA01", "URBA02", "URBA03", "URBA04", "URBA05", "DUSO01", "DUSO02", "DUSO03", "DUSO04", "ALLEG3", "ALLG31", "SISVAL", "SUADEG", "NORMA1", "DESPRO1", "SHAPE_AREA", "SHAPE_LEN", "ID1") VALUES (%(auto_pk)s, %(geom)s, %(LIVELLO)s, %(ST)s, %(SA)s, %(W)s, %(NAM)s, %(ISOLATO)s, %(UNITAED)s, %(UNITAEL)s, %(ATTRFAB)s, %(PORTICO)s, %(NUMALLO)s, %(NUMALTR)s, %(NUMPIAN)s, %(AREPERT)s, %(CONSERV)s, %(SEMINTE)s, %(TIPOGODI)s, %(TIPOUED)s, %(DESUSAS)s, %(SUPERF)s, %(DATAUAG)s, %(DESCOPE)s, %(TIPOLED)s, %(TRASFED)s, %(NORMA)s, %(DESTPIAN)s, %(CATEDIFI)s, %(VINCOL1)s, %(ART1)s, %(VINCOL2)s, %(ART2)s, %(TIPOPRO)s, %(NOTESTO)s, %(NOTA1)s, %(NOTA2)s, %(NOTA3)s, %(NOTA4)s, %(NOTA5)s, %(NOTA6)s, %(NOTA7)s, %(NOTA8)s, %(NOTA9)s, %(NOTA10)s, %(NOTA11)s, %(PARSUOLO)s, %(MANINSTO)s, %(TIPOLE1)s, %(TRASFE1)s, %(CLASSE)s, %(TIPOLIN)s, %(TIPOLI1)s, %(TIPOLI2)s, %(DESSER)s, %(DESPRO)s, %(SISBAS)s, %(STRUATT)s, %(PIANO1)s, %(PIANO2)s, %(PIANO3)s, %(PIANO4)s, %(URBA01)s, %(URBA02)s, %(URBA03)s, %(URBA04)s, %(URBA05)s, %(DUSO01)s, %(DUSO02)s, %(DUSO03)s, %(DUSO04)s, %(ALLEG3)s, %(ALLG31)s, %(SISVAL)s, %(SUADEG)s, %(NORMA1)s, %(DESPRO1)s, %(SHAPE_AREA)s, %(SHAPE_LEN)s, %(ID1)s)]
[parameters: ({'auto_pk': 3968, 'geom': <psycopg2.extensions.Binary object at 0x7fe02e4ff3f0>, 'LIVELLO': '15', 'ST': '0', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '2761', 'UNITAED': '10', 'UNITAEL': '10', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '0', 'NUMALTR': '0', 'NUMPIAN': '0', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '0', 'TIPOGODI': 'PRIVATO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'CORTILE-CORTE', 'SUPERF': '125.2212999999999993860910763032734394073486328125', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': None, 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': None, 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': None, 'SHAPE_AREA': '125.202010000000001355147105641663074493408203125', 'SHAPE_LEN': '58.0050499999999971123543218709528446197509765625', 'ID1': '3968'}, {'auto_pk': 3969, 'geom': <psycopg2.extensions.Binary object at 0x7fe02e4ff420>, 'LIVELLO': '15', 'ST': '0', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '2810', 'UNITAED': '18', 'UNITAEL': '10', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '0', 'NUMALTR': '0', 'NUMPIAN': '0', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '0', 'TIPOGODI': 'PRIVATO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'GIARDINO-ORTO', 'SUPERF': '63.365240000000000009094947017729282379150390625', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': None, 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': None, 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': None, 'SHAPE_AREA': '63.3590099999999978308551362715661525726318359375', 'SHAPE_LEN': '35.96049000000000006593836587853729724884033203125', 'ID1': '3969'}, {'auto_pk': 3970, 'geom': <psycopg2.extensions.Binary object at 0x7fe02e4ff450>, 'LIVELLO': '15', 'ST': '0', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '1950', 'UNITAED': '29', 'UNITAEL': '50', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '0', 'NUMALTR': '0', 'NUMPIAN': '0', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '0', 'TIPOGODI': 'PRIVATO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'CORTILE-CORTE', 'SUPERF': '730.41534000000001469743438065052032470703125', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': None, 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': None, 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': None, 'SHAPE_AREA': '730.4260000000000445652403868734836578369140625', 'SHAPE_LEN': '139.80905000000001336957211606204509735107421875', 'ID1': '3970'}, {'auto_pk': 3971, 'geom': <psycopg2.extensions.Binary object at 0x7fe02e4ff480>, 'LIVELLO': '15', 'ST': '0', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '710', 'UNITAED': '9', 'UNITAEL': '10', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '0', 'NUMALTR': '0', 'NUMPIAN': '0', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '0', 'TIPOGODI': 'PRIVATO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'CORTILE-CORTE', 'SUPERF': '105.9117499999999978399500832892954349517822265625', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': None, 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': None, 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': None, 'SHAPE_AREA': '105.8933799999999934016159386374056339263916015625', 'SHAPE_LEN': '48.85108000000000316731529892422258853912353515625', 'ID1': '3971'}, {'auto_pk': 3972, 'geom': <psycopg2.extensions.Binary object at 0x7fe02e4ff4b0>, 'LIVELLO': '15', 'ST': '0', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '770', 'UNITAED': '10', 'UNITAEL': '20', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '0', 'NUMALTR': '0', 'NUMPIAN': '0', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '0', 'TIPOGODI': 'PRIVATO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'GIARDINO-ORTO', 'SUPERF': '123.943569999999994024619809351861476898193359375', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': None, 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': None, 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': None, 'SHAPE_AREA': '123.943389999999993733581504784524440765380859375', 'SHAPE_LEN': '46.68113000000000312184056383557617664337158203125', 'ID1': '3972'}, {'auto_pk': 3973, 'geom': <psycopg2.extensions.Binary object at 0x7fe02e4ff4e0>, 'LIVELLO': '15', 'ST': '0', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '710', 'UNITAED': '16', 'UNITAEL': '10', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '0', 'NUMALTR': '0', 'NUMPIAN': '0', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '0', 'TIPOGODI': 'PRIVATO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'CORTILE-CORTE', 'SUPERF': '110.2998099999999936926542432047426700592041015625', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': None, 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': None, 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': None, 'SHAPE_AREA': '110.301659999999998262865119613707065582275390625', 'SHAPE_LEN': '47.9279099999999971259967423975467681884765625', 'ID1': '3973'}, {'auto_pk': 3974, 'geom': <psycopg2.extensions.Binary object at 0x7fe02e4ff510>, 'LIVELLO': '15', 'ST': '0', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '1950', 'UNITAED': '5', 'UNITAEL': '10', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '0', 'NUMALTR': '0', 'NUMPIAN': '0', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '0', 'TIPOGODI': 'PRIVATO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'CORTILE-CORTE', 'SUPERF': '53.21679999999999921556081972084939479827880859375', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': None, 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': None, 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': None, 'SHAPE_AREA': '53.2116299999999995407051756046712398529052734375', 'SHAPE_LEN': '29.868700000000000471800376544706523418426513671875', 'ID1': '3974'}, {'auto_pk': 3975, 'geom': <psycopg2.extensions.Binary object at 0x7fe02e4ff540>, 'LIVELLO': '15', 'ST': '0', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '360', 'UNITAED': '16', 'UNITAEL': '20', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '0', 'NUMALTR': '0', 'NUMPIAN': '0', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '0', 'TIPOGODI': 'PRIVATO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'CORTILE-CORTE', 'SUPERF': '38.17969000000000079353412729687988758087158203125', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': None, 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': None, 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': None, 'SHAPE_AREA': '38.17549000000000347654349752701818943023681640625', 'SHAPE_LEN': '28.046730000000000160298441187478601932525634765625', 'ID1': '3975'}  ... displaying 10 of 4966 total bound parameter sets ...  {'auto_pk': 4973, 'geom': <psycopg2.extensions.Binary object at 0x7fe02eda9a70>, 'LIVELLO': '15', 'ST': '', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '255', 'UNITAED': '1', 'UNITAEL': '1', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '', 'NUMALTR': '', 'NUMPIAN': '', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '', 'TIPOGODI': 'PUBBLICO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'AREA DEMANIALE', 'SUPERF': '13870.61', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': 'MILITARE', 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': '', 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': 'ATTREZZATURE DI INTERESSE COMUNE', 'SHAPE_AREA': '13870.60548', 'SHAPE_LEN': '1555.28463', 'ID1': '2606'}, {'auto_pk': 4974, 'geom': <psycopg2.extensions.Binary object at 0x7fe02eda9aa0>, 'LIVELLO': '15', 'ST': '', 'SA': '0', 'W': '45', 'NAM': 'A', 'ISOLATO': '255', 'UNITAED': '1', 'UNITAEL': '1', 'ATTRFAB': '11', 'PORTICO': None, 'NUMALLO': '', 'NUMALTR': '', 'NUMPIAN': '', 'AREPERT': None, 'CONSERV': None, 'SEMINTE': '', 'TIPOGODI': 'PUBBLICO', 'TIPOUED': 'EDIFICATO', 'DESUSAS': 'AREA DEMANIALE', 'SUPERF': '13870.61', 'DATAUAG': None, 'DESCOPE': None, 'TIPOLED': None, 'TRASFED': None, 'NORMA': None, 'DESTPIAN': None, 'CATEDIFI': None, 'VINCOL1': None, 'ART1': None, 'VINCOL2': None, 'ART2': None, 'TIPOPRO': 'MILITARE', 'NOTESTO': None, 'NOTA1': None, 'NOTA2': None, 'NOTA3': None, 'NOTA4': None, 'NOTA5': None, 'NOTA6': None, 'NOTA7': None, 'NOTA8': None, 'NOTA9': None, 'NOTA10': None, 'NOTA11': None, 'PARSUOLO': None, 'MANINSTO': None, 'TIPOLE1': None, 'TRASFE1': None, 'CLASSE': None, 'TIPOLIN': None, 'TIPOLI1': None, 'TIPOLI2': None, 'DESSER': None, 'DESPRO': '', 'SISBAS': None, 'STRUATT': None, 'PIANO1': None, 'PIANO2': None, 'PIANO3': None, 'PIANO4': None, 'URBA01': None, 'URBA02': None, 'URBA03': None, 'URBA04': None, 'URBA05': None, 'DUSO01': None, 'DUSO02': None, 'DUSO03': None, 'DUSO04': None, 'ALLEG3': None, 'ALLG31': None, 'SISVAL': None, 'SUADEG': None, 'NORMA1': None, 'DESPRO1': 'ATTREZZATURE DI INTERESSE COMUNE', 'SHAPE_AREA': '13870.60548', 'SHAPE_LEN': '1555.28463', 'ID1': '2606'})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

**Version Info **
 - OS: Ubuntu 20.04
 - Version: 
 - Kart v0.12.3, Copyright (c) Kart Contributors
      GDAL v3.6.3; PROJ v9.2.0; PDAL v2.4.3
      PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
      SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.1; SpatiaLite v5.0.1; Libpq v15.0.2

**Comment by enricofer** [comment]
I tried to reproduce the issue creating a new repo from scratch, importing the affected ds and introducing NULL values on numeric fields and everything seems fine. So the issue appears related to the provided faulty repo

**Comment by enricofer** [comment]
I solved my problem completely removing the features that generate NULL exception and recreating them from scratch

**Comment by craigds** [comment]
This looks like it was caused by #863

**Comment by olsen232** [comment]
So #863 which craigds mentioned above is a pretty serious Kart issue - some code that was supposed to trim trailing zeros from a decimal point eg "1.020" -> "1.02" would, in certain circumstances, trim other trailing zeroes too eg "1020" -> "102" or even "0" -> "". This only happens when reading numerics from PG and the numeric has a scale of 0, or is unconstrained and has no decimal places after a decimal point.
Due to this bug, the dataset in your kart repo may now be different from the dataset you imported it from, or the data that you committed to it. Try have a look to see if your data has been affected. You can run `kart create-workingcopy` to have Kart recreate your working copy to make sure that the data in your working copy accurately reflects that which Kart has stored.
We've spent the past few days adding more tests to make sure data-loss bugs like this one don't happen again, and working on getting a release out. [Release 0.13.0](https://github.com/koordinates/kart/releases/tag/v0.13.0) has a fix - if your data has issues and you can't find a way to manually patch it up, you can use Kart 0.13 to start over.

**Comment by enricofer** [comment]
Installing kart 0.13 resolves the issue. Thank you very much for the solution.
