### ISSUE TITLE
[removed]

### ISSUE THREAD

**Issue by Kaessham** [koordinates/kart#910]
**Describe the bug**

→ If you're using the QGIS plugin, please file your issue at the [plugin project](https://github.com/koordinates/kart-qgis-plugin/issues/new/choose).

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
What did you expect to happen?

**Output**
Add the output you're seeing to help explain your problem.

**Version Info **
 - OS: [e.g. Windows 10]
 - Version: [from `kart version`]

**Comment by craigds** [comment]
This looks like spam. If it's a real issue, please re-submit - be careful to avoid posting sensitive information.
