### ISSUE TITLE
Documentation around remotes and hosting

### ISSUE THREAD

**Issue by arkore** [koordinates/kart#923]
Browsing the documentation and the repo it's not clear how to setup remotes for use with kart. Is it possible to host on a standard git repo, is there a special kart git server to host a repo? Are there any differences in terms of repo hosting from git at all when using kart? 

Would love to see a basic statement about hosting a repo. 

I've checked most of the docs, searched issues and the docs for "remote" but could not find an answer.

**Comment by arkore** [comment]
So by explicitly testing I can see that as I suspected, kart works with any git hosting service. Just need to update the docs now.

**Comment by olsen232** [comment]
@arkore added a paragraph to the basic usage tutorial, I added a bit of info to it about spatial filtered clones (which is the special case where the regular Git can't do everything that Kart's special Git can). Closing for now, but everyone should feel free to contribute more documentation on this topic or any other wherever they find it to be lacking
